# Generated by Django 5.2 on 2025-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='table',
            name='time_slots',
            field=models.ManyToManyField(through='bookings.TableTimeSlot', to='bookings.timeslot', verbose_name='Horarios'),
        ),
    ]
