# Generated by Django 5.2 on 2025-06-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_table_capacity_alter_table_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
