# Generated by Django 5.2.1 on 2025-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_user_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
